data_lookup_index : "/home/arr65/data/nzgd/nzgd_index_files/csv_files/NZGD_Investigation_Report_25092024_1043.csv"
load_wait_time_s : 15
number_of_processes : 6

high_level_download_dir : "/home/arr65/data/nzgd/downloaded_files/active_download"
login_url : 'https://www.nzgd.org.nz/Registration/Login.aspx'

downloaded_record_note_per_record : "/home/arr65/data/nzgd/downloaded_record_note_per_record"
name_to_files_dir_per_record : "/home/arr65/data/nzgd/name_to_files_dicts_per_record"
name_to_link_str_dir_per_record : "/home/arr65/data/nzgd/name_to_link_str_dicts_per_record"
name_to_metadata_dir_per_record : "/home/arr65/data/nzgd/name_to_metadata_per_record"