data_lookup_index : "/home/arr65/data/nzgd/nzgd_index_files/csv_files/NZGD_Investigation_Report_19092024_1045.csv"
load_wait_time_s : 5
number_of_processes : 8

high_level_download_dir : "/home/arr65/data/nzgd/downloaded_files/download_run_4"
login_url : 'https://www.nzgd.org.nz/Registration/Login.aspx'

downloaded_record_note_per_record : "/home/arr65/data/nzgd/downloaded_record_note_per_record"
name_to_files_dir_per_record : "/home/arr65/data/nzgd/name_to_files_dicts_per_record"
name_to_link_str_dir_per_record : "/home/arr65/data/nzgd/name_to_link_str_dicts_per_record"