data_lookup_index : "/home/arr65/data/nzgd/nzgd_index_files/csv_files/NZGD_Investigation_Report_23102024_1042.csv"
load_wait_time_s : 15
number_of_processes : 6

high_level_download_dir : "/home/arr65/data/nzgd/downloads_and_metadata/23102024"
login_url : 'https://www.nzgd.org.nz/Registration/Login.aspx'

downloaded_record_note_per_record : "/home/arr65/data/nzgd/downloads_and_metadata/23102024/downloads_metadata/downloaded_record_note_per_record"
name_to_files_dir_per_record : "/home/arr65/data/nzgd/downloads_and_metadata/23102024/downloads_metadata/name_to_files_dicts_per_record"
name_to_link_str_dir_per_record : "/home/arr65/data/nzgd/downloads_and_metadata/23102024/downloads_metadata/name_to_link_str_dicts_per_record"
name_to_metadata_dir_per_record : "/home/arr65/data/nzgd/downloads_and_metadata/23102024/downloads_metadata/name_to_metadata_per_record"